security:
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

#    header: Authorization
#    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#    token-validty-in-seconds: 86400

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

#servers:
#  - url: http://i9a307.p.ssafy.io/
#    description: Production server

# access-key와 secret-key는 반드시 gitignore 확인!!!!!!
# 두번 확인 !!!!
cloud:
  aws:
    credentials:
      access-key: AKIASUML2QGY2ZDUQV6P
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false